# Generated by Django 5.2.6 on 2025-10-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucandidate',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_candidates', to='restaurant.restaurant'),
        ),
        migrations.AddIndex(
            model_name='menucandidate',
            index=models.Index(fields=['restaurant', 'name'], name='menu_menuca_restaur_9b8322_idx'),
        ),
    ]
