# Generated by Django 5.2.7 on 2025-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0002_initial"),
        ("books", "0005_remove_book_authors_remove_book_genres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartercounter",
            name="offered_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="counter_offered_books",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="bartercounter",
            name="requested_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="counter_requested_books",
                to="books.bookcopy",
            ),
        ),
    ]
