# Generated by Django 5.2.7 on 2025-11-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0002_initial"),
    ]

    operations = [
        # Original migration attempted to convert the UUID primary key
        # into an AutoField (integer). That cast breaks on PostgreSQL,
        # and the project now relies on UUIDs everywhere, so this
        # migration intentionally does nothing.
    ]
