# Generated by Django 5.2.8 on 2025-11-16 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0006_alter_barterrequest_id"),
        ("books", "0004_remove_book_books_book_availab_7c5efd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barterrequest",
            name="offered_book_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of 3 book IDs proposed by requester",
            ),
        ),
        migrations.AlterField(
            model_name="barterrequest",
            name="offered_book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book offered by the requester (final selection by recipient)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_in_barters",
                to="books.book",
            ),
        ),
    ]
