# Generated by Django 5.2.7 on 2025-12-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userpreference_rl_weight_vector_rlweighthistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRemoteScrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_id", models.CharField(max_length=100)),
                ("menu_name", models.CharField(max_length=200)),
                ("place_name", models.CharField(max_length=200)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True)),
                ("coordinates", models.JSONField(blank=True, default=list)),
                ("scrapped_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_scraps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "synced_at"],
                        name="users_userr_user_id_a463fa_idx",
                    ),
                    models.Index(
                        fields=["user", "menu_id"],
                        name="users_userr_user_id_1f70db_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "menu_id"), name="uniq_user_remote_scrap"
                    )
                ],
            },
        ),
    ]
