# Generated by Django 5.2.8 on 2025-11-16 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_remove_book_books_book_availab_7c5efd_idx_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_isbn_13_a77f18_idx",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="isbn_13",
            new_name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn_10",
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["isbn"], name="books_book_isbn_54becd_idx"
            ),
        ),
    ]
