# Generated by Django 5.2.7 on 2025-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookpublication_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublication',
            name='category_scores',
            field=models.JSONField(blank=True, default=list, help_text='Cached LLM category scores (label + score dicts)'),
        ),
        migrations.AddField(
            model_name='bookpublication',
            name='taste_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Cached LLM taste profile (genres, moods, purposes, length)'),
        ),
    ]
