# Generated by Django 5.2.7 on 2025-11-04 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_id'),
        ('books', '0002_alter_bookreview_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Delete all existing posts since UUID -> int conversion requires data migration
        migrations.RunSQL(
            sql='DELETE FROM social_post;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Remove foreign key constraints first
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to='social.post',
                db_constraint=False,
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='social.post',
                db_constraint=False,
            ),
        ),
        
        # Now change the id field type
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        
        # Restore foreign key constraints
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to='social.post',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='social.post',
            ),
        ),
    ]
