# Generated by Django 5.2.7 on 2025-11-04 05:12

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_id'),
        ('books', '0002_alter_bookreview_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Delete models first (works on both SQLite and PostgreSQL)
        migrations.DeleteModel(name='Comment'),
        migrations.DeleteModel(name='PostLike'),
        migrations.DeleteModel(name='Post'),
        
        # Recreate Post table with integer ID
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(
                    choices=[
                        ('text', 'Text Post'),
                        ('book_review', 'Book Review'),
                        ('barter_offer', 'Barter Offer'),
                    ],
                    max_length=20,
                    default='text'
                )),
                ('content', models.TextField(help_text='Share your thoughts about books!')),
                ('image', models.ImageField(upload_to='post_images/', null=True, blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='posts',
                    to=settings.AUTH_USER_MODEL
                )),
                ('related_book', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='related_posts',
                    to='books.book',
                    help_text='Book this post is about (optional)'
                )),
            ],
            options={
                'db_table': 'social_post',
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['author'], name='social_post_author_idx'),
                    models.Index(fields=['post_type'], name='social_post_type_idx'),
                    models.Index(fields=['created_at'], name='social_post_created_idx'),
                    models.Index(fields=['is_public'], name='social_post_public_idx'),
                ],
            },
        ),
        
        # Recreate PostLike table
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_post_like',
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'unique_together': {('post', 'user')},
            },
        ),
        
        # Recreate Comment table (UUID id, max_length=500)
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to=settings.AUTH_USER_MODEL
                )),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='social.post'
                )),
                ('parent_comment', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='replies',
                    to='social.comment'
                )),
            ],
            options={
                'db_table': 'social_comment',
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['post'], name='social_comm_post_id_000da3_idx'),
                    models.Index(fields=['author'], name='social_comm_author__29a094_idx'),
                    models.Index(fields=['created_at'], name='social_comm_created_082b02_idx'),
                ],
            },
        ),
        
        # Add ManyToMany field for Post.likes
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(
                blank=True,
                related_name='liked_posts',
                through='social.PostLike',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Add indexes for Post (already in Meta but need to add separately)
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='social_post_author__3bb785_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='social_post_post_ty_d10c83_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='social_post_created_31587b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_public'], name='social_post_is_publ_afc947_idx'),
        ),
    ]
