# Generated by Django 5.2.6 on 2025-10-17 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'user'), ('menu', 'menu'), ('image', 'image'), ('restaurant', 'restaurant')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('embedding', models.JSONField(blank=True, default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='recommendat_entity__f64df3_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='uniq_embedding_entity')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(blank=True)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('recommended_menu_ids', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rankings', to='menu.menu')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='recommendation.recommendationresult')),
            ],
        ),
        migrations.AddIndex(
            model_name='recommendationresult',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_646f54_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationranking',
            index=models.Index(fields=['recommendation', 'rank'], name='recommendat_recomme_2698cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationranking',
            constraint=models.UniqueConstraint(fields=('recommendation', 'menu'), name='uniq_recommendation_menu'),
        ),
    ]
