# Generated by Django 5.2.7 on 2025-11-02 12:25

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DbRestaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.TextField()),
                ("category", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("road_address", models.TextField(blank=True, null=True)),
                ("group1", models.TextField(blank=True, null=True)),
                ("group2", models.TextField(blank=True, null=True)),
                ("group3", models.TextField(blank=True, null=True)),
                ("category_code", models.TextField(blank=True, null=True)),
                (
                    "category_code_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "place_images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_normalized", models.TextField(blank=True, null=True)),
                ("meaningful_name", models.BooleanField(default=False)),
                ("inferred_menu", models.TextField(blank=True, null=True)),
                (
                    "embedding_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "db_table": "db_restaurants",
            },
        ),
        migrations.CreateModel(
            name="DbMenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField()),
                ("price", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("recommend", models.BooleanField(default=False)),
                ("index_in_rest", models.IntegerField(blank=True, null=True)),
                ("name_clean", models.TextField(blank=True, null=True)),
                ("taste_profile", models.JSONField(blank=True, null=True)),
                ("allergen_info", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        db_column="restaurant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psql_data.dbrestaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "db_table": "db_menus",
            },
        ),
    ]
