# Generated by Django 5.2.7 on 2025-11-03 06:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psql_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbrestaurant',
            name='geom',
            field=models.TextField(blank=True, help_text='PostGIS geometry field stored as text', null=True),
        ),
        migrations.AlterField(
            model_name='dbmenu',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dbmenu',
            name='id',
            field=models.UUIDField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dbrestaurant',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dbrestaurant',
            name='external_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dbrestaurant',
            name='id',
            field=models.UUIDField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dbrestaurant',
            name='inferred_menu',
            field=models.TextField(blank=True, default=''),
        ),
    ]
