# Generated by Django 5.2.7 on 2025-11-03 06:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psql_data', '0002_dbrestaurant_geom_alter_dbmenu_embedding_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmenu',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dbrestaurant',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
